ALTER TABLE `payment_requests` ADD `category` text DEFAULT 'Lain-lain' NOT NULL;--> statement-breakpoint
UPDATE `payment_requests`
SET `category` = CASE
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%ongkir%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%pengiriman%'
    THEN 'Ongkir / Pengiriman'
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%komisi%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%bagi hasil%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%net profit%'
    OR lower(`description`) LIKE '%bbr 50%'
    OR lower(`description`) LIKE '%mpm 50%'
    OR lower(`description`) = 'bbr ajb 137'
    THEN 'Komisi & Bagi Hasil'
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%gaji%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%salary%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%bonus%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%overtime%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%lembur%'
    THEN 'Gaji & Karyawan'
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%operasional%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%petty cash%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%patty cash%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%rental%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%perbaikan%'
    OR lower(`description`) LIKE '%pc purchasing%'
    OR lower(`description`) LIKE '%fitri cell%'
    THEN 'Biaya Operasional'
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%hasil penjualan%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%keep modal%'
    THEN 'Dana Masuk/Keluar Lainnya'
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%part%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%stock%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%stok%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%supplier%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%nota%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%pembelian%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%gasket%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%spring%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%bearing%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%filter%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%compressor%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%brake drum%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%rivet%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%v-belt%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%ban %'
    THEN 'Beli Barang / Spare Part'
  WHEN lower(`description` || ' ' || `transaction_purpose`) LIKE '%investor%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%modal%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%refund%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%reimburse%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%angsuran%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%kpr%'
    OR lower(`description` || ' ' || `transaction_purpose`) LIKE '%prive%'
    THEN 'Dana Masuk/Keluar Lainnya'
  ELSE 'Lain-lain'
END;--> statement-breakpoint
CREATE INDEX `payment_requests_category_idx` ON `payment_requests` (`category`);
